name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file docker-file-ubuntu -t docker.pkg.github.com/${{ github.repository }}/ubuntu-xsar:${{ github.sha }}
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/${{ github.repository }}/ubuntu-xsar:${{ github.sha }}
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          docker.pkg.github.com/${{ github.repository }}/ubuntu-xsar:${{ github.sha }}
          docker.pkg.github.com/${{ github.repository }}/ubuntu-xsar:${{ github.ref }}
