name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker-file-ubuntu -t docker.pkg.github.com/alevieux/docker-image-xsar/ubuntu-xsar:latest
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/alevieux/docker-image-xsar/ubuntu-xsar:latest
